### ISSUE TITLE
New Check: AvoidFinalConditionInversion

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#112]
We need a check that could catch "not" operator - "!" (an exclamation mark) that is used as final operation, but it is possible without changing a meaning of condition change its parts to make condition more readable.

Bad code examples:
isDifferent(): return ! (a == b); ==should be==> return a != b;
isLower(): boolean c = !(a > b); ==should be==> boolean c = a <= b;
isLowerLimits(): if (! ((a>=8) && (b>=5)) ) ==should be==> if ((a<8) || (b<5)) 

Big example (not sure we could catch such cases):

```
return !(timeLoadMlls < maxMasterSymbolLoadStampMills 
          && fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART) 
          || timeLoadMlls < maxOtherLoadStampMills 
          && !fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART));
```

==should be==>

```
return (timeLoadMlls >= maxMasterSymbolLoadStampMills 
           || !fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART) 
           && timeLoadMlls >= maxOtherLoadStampMills 
           || fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART));
```

**Comment by rdiachenko** [comment]
>> 
if (! ((a>=8) && (b>=5)) ) ==should be==> if ((a<8) && (b<5))

---------------------------------
>> 
return !(timeLoadMlls < maxMasterSymbolLoadStampMills 
&& fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART) 
|| timeLoadMlls < maxOtherLoadStampMills 
&& !fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART));
==should be==>
return (timeLoadMlls >= maxMasterSymbolLoadStampMills 
&& fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART) 
|| timeLoadMlls >= maxOtherLoadStampMills 
&& !fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART));

According to <a href="https://en.wikipedia.org/wiki/De_Morgan%27s_laws">De Morgan's lows</a> the resulted expressions should be as follows:

```
if (! ((a>=8) && (b>=5)) ) ==should be==> if ((a<8) || (b<5))
```

and

```
return !(timeLoadMlls < maxMasterSymbolLoadStampMills 
&& fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART) 
|| timeLoadMlls < maxOtherLoadStampMills 
&& !fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART));

==should be==>

return (timeLoadMlls >= maxMasterSymbolLoadStampMills 
|| !fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART) 
&& timeLoadMlls >= maxOtherLoadStampMills 
|| fileName.toLowerCase().contains(MASTER_SYMBOL_NAME_PART));
```

**Comment by romani** [comment]
description was updated.
