### ISSUE TITLE
Prevent using packages/classes from classes

### ISSUE THREAD

**Issue by ilumar** [sevntu-checkstyle/sevntu.checkstyle#135]
Create check that will be prevent using packages/classes from classes that matches to pattern. 

We already have forbidding packages in packages, see below:
See check that control base on packages: http://checkstyle.sourceforge.net/config_imports.html#ImportControl
See other check that do package to package rules: https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.java

Example: we want to forbid usage of dao package ("._.dao._") in presentation models files (that match pattern like ".*Pm.java")

**Comment by rnveach** [comment]
@romani This looks the same as [issue in main project](https://github.com/checkstyle/checkstyle/issues/3492), or am i mistaken?

**Comment by romani** [comment]
right, problem is the same.
sevntu issue is not required.
