### ISSUE TITLE
Resolve problems in code detected by Sonar

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#169]
http://nemo.sonarqube.org/dashboard/index/com.github.sevntu.checkstyle:sevntu-checks

Sonar make sense :) .

**Comment by rnveach** [comment]
@romani How do you run sonar for latest changes we made?
Last run seems to be May 31st 2016.

**Comment by romani** [comment]
It is up to sonar web service, loos like smth is brocken on their side.

**Comment by rnveach** [comment]
There is no way to enforce even current state of violations
In some near future they will create ability to adjust rules by us
After that we could start bothering

I am closing this for now.
