### ISSUE TITLE
new Check: RegexpOnFilename

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#256]
from : https://groups.google.com/forum/#!topic/sevntu-checkstyle/W1Kt3K1-8R8

This check applies a given regular expression to the names of files. Depending on the configuration, a warning is logged if a required match is not found, or if an illegal match is found.
This is useful for situations such as:
Checking that resources in certain directories follow a naming convention
Resource file names contain only legal characters
Files of certain types are created in the right places, e.g. Java files under src/*/java
Prevent certain files or types of files altogether, by "banning" their names
By default, this check flags leading and trailing spaces in file names.

targetFolderPattern - regular expression that will be applied to canonical folder location of the file. It does not contains filename, only folder/directory. 
fileNamePattern -  regular expression that will be applied to filename (with extension).
match - boolean option. TRUE - report matching of files by Paterns (message regexp.filepath.match will be used) , FALSE - report all mismatching of files by Paterns (message regexp.filepath.mismatch will be used)

```
<module name="RegexpOnFilename">
  <property name="targetFolderPattern" value="[\\/]src[\\/](?:test|main)[\\/]java[\\/]"/>
  <property name="fileNamePattern" value="*.java"/>
  <property name="match" value="false"/>
  <message key="regexp.filepath.mismatch" value="The Java file ''{0}'' must reside in a Java source folder."/>
</module>

<module name="RegexpOnFilename">
  <property name="targetFolderPattern" value="[\\/]src[\\/]main[\\/]resources[\\/]html[\\/]views[\\/]"/>
  <property name="fileNamePattern" value="^view_.*"/>
  <property name="match" value="true"/>
  <message key="regexp.filepath.match" value="Name of ''{0}'' must start with ''view_''."/>
</module>

<module name="RegexpOnFilename">
  <property name="fileNamePattern" value="*.gif"/>
  <message key="regexp.filepath.match" value="''{0}'' must be in PNG format, not GIF."/>
</module>
```

**Comment by romani** [comment]
@melodicwing , do you still plan to tackle that issue ?

**Comment by melodicwing** [comment]
@romani yes, i am working on it

**Comment by romani** [comment]
@melodicwing , pas you have time, please describe at mailist there you are in design or implementation, i need to verify that you are on a right way of implementation

**Comment by tsjensen** [comment]
@melodicwing Please note that the original idea for this check [is mine](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/206). I am also the author of the original implementation, which I published [here](http://checkstyle-addons.thomasjensen.com/latest/checks/regexp.html#RegexpOnFilename) in the meantime.
Of course you may do your own reimplementation for SevNTU Checkstyle (Roman has very specific requirements which my implementation does not meet, as you can see from the [history of this check's dicsussion](https://groups.google.com/forum/#!topic/sevntu-checkstyle/W1Kt3K1-8R8)), but please be sure to provide appropriate credit. Thank you.

**Comment by romani** [comment]
We do not provide credits at java doc for ideas, credits for ideas are only at issue tracker. If author of implementation decide to reuse your code only in that case it make sense to reference you.

**Comment by tsjensen** [comment]
Well, if it wasn't for my own comment, even the issue tracker would've had no mention (unless people go researching). What harm is there in being fair?

**Comment by romani** [comment]
you participated at mail-list - so there are plenty of credits.
I did mention of idea source as first sentence of issue.
It is enough.

you can be referenced in java file only if you participate in development of it.

I other case I need to reference the whole java community in that files, as ideas a gathered from number of Stackoverflow problems and blogs owners and all developers of Google and Oracle/Sun. And in addition to that I need to put a credit to their mothers as only due to them we have so bright contributors.......... 

Only actual work is give a credit in place where it was done. Give an idea is not enough, even contribution of some code is not enough as we need full solution and code with certain level of quality and wide testing.

I need that tag only to understand to whom I  can connect to resolve additional problems that found in Check after merge and release. In most projects that tag is banned, as it provide no useful information. One day might remove that tag completely from code to avoid such discussions in future.

If you need some valuable credentials , please make sure that you have link in your CV like - https://github.com/checkstyle/checkstyle/commits/master?author=mkordas .

**Comment by tsjensen** [comment]
I don't "need credentials" from you, Roman, don't worry. ;-)
I just don't like you to take credit for an idea that was mine, which should go without saying.

**Comment by romani** [comment]
> I just don't like you to take credit for an idea that was mine 

I never claimed it to be my idea, I gave a ref from there it is taken, please read first line of issue description. All I did is just put it in dev plan, to not forget to implement eventually.

**Comment by melodicwing** [comment]
@romani sorry, but in the near future i can't work on this issue or any another issue. no time

**Comment by rnveach** [comment]
closing this issue as check was created in main project
http://checkstyle.sourceforge.net/config_regexp.html#RegexpOnFilename
