### ISSUE TITLE
Checkstyle Package XML should be in core library JAR

### ISSUE THREAD

**Issue by dhumeniuk** [sevntu-checkstyle/sevntu.checkstyle#259]
According to http://checkstyle.sourceforge.net/config.html#Packages, the package XML file should be in the root of the JAR providing the additional checks (sevntu-checks project) and is currently not. This would allow just the classname to be specified in the checks file like is done by the Eclipse plug-in.

See discussion here too: https://groups.google.com/forum/#!topic/sevntu-checkstyle/Krhy6UYeOAI

**Comment by rnveach** [comment]
Closing as file was added
