### ISSUE TITLE
Get NullPointerException if MapIterationInForEachLoop is enabled

### ISSUE THREAD

**Issue by maxvetrenko** [sevntu-checkstyle/sevntu.checkstyle#261]
27 September. From [kmart216](https://github.com/kmart216):

Rule is in configuration as:

    <module name="com.github.sevntu.checkstyle.checks.coding.MapIterationInForEachLoop"/>

Code example:

    public void someMethod()
    {
        final ArrayList<Integer> keySet = new ArrayList<Integer>();
        for (int key : keySet)
        {
            System.out.println(key);
        }
    }

**Comment by romani** [comment]
that is caused by bracking compatibility in checkstyle, should be fine in next release
