### ISSUE TITLE
Create a test/tool to validate the synchronization of config files with changes in checks

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#285]
**Problem:**
When we create/modify/remove checks we have to keep in mind the following resources which have to be updated as well:

1) <a href="https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/gh-pages/sevntu-checkstyle-default-configuration.xml">SevNTU checkstyle default configuration</a>
2) <a href="https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml">SevNTU checkstyle sonar configuration</a>

As we're all human beings we forget to update these resources from time to time. (One of the examples: #283)

**Proposal:**
We should create some kind of test/tool which will check if all resources are properly updated after regular changes in checks. It'll be also good to integrate this test into maven build and fail the whole build until a developer updates all the resources.

**Comment by damianszczepanik** [comment]
I've done it already for code coverage in https://github.com/damianszczepanik/sevntu.checkstyle/commit/a2f6734b0e3140021e56912e29fba8a264a98539 so I expect validating against checkstyle rules should work similar.

Have you prepared list of rules that shall be applied? I expect some of them are similar to Sonar but Sonar uses different approach and may check more than checkstyle (PMD, FindBugs).

We'd better start to clean #169 and then this one would be easier because we will not have exception for each class :)

**Comment by rdiachenko** [comment]
Let's look at the problem from another angle: consider creating a sort of config generator. It can be a tool which can generate the required configurations from the source code.

**Comment by rnveach** [comment]
Validation of sonar's `checkstyle-extensions.xml` and eclipse-cs `checkstyle-metadata.xml` and `checkstyle-metadata.properties` is done.
`sevntu-checkstyle-default-configuration.xml` is not done, but a copy was moved to main branch which is automated against.
@romani Please confirm we still want the last item done, and if so, were missing checks should go in that config as it is order by release and main branch was ordered by package.

**Comment by romani** [comment]
Lets skip this file for now, as we already have a copy.

**Comment by romani** [comment]
Please reference commit where fix was done for validation and close the issue

**Comment by rnveach** [comment]
sonar was started in Pull #487 
eclipse-cs was started in Pull #495 
Issue #506 made sure all sevntu checks were referenced in the config
