### ISSUE TITLE
Combine code for reporting invalid token into one utility method

### ISSUE THREAD

**Issue by damianszczepanik** [sevntu-checkstyle/sevntu.checkstyle#308]
Many classes/checkers (in fact all of them should) report unsupported token in different ways. Following piece of code can be found in a few classes:

          default:
                 final String className = this.getClass().getSimpleName();
                 final String tokenType = TokenTypes.getTokenName(ast.getType());
                 final String tokenDescription = ast.toString();
                 final String message = String.format("%s got the wrong input token: %s (%s)",
                                         className, tokenType, tokenDescription);
                 throw new IllegalArgumentException(message);

That would be nice to have one 'utility' method eg in Check class that can be reused for such cases.

**Comment by romani** [comment]
previously I tried to avoid any Utils classes as in main project Util is api , but recently we started process ov moving util out of api - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Utils.java

Please create Util.java here as analog to main project -
https://github.com/sevntu-checkstyle/sevntu.checkstyle/tree/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle
