### ISSUE TITLE
Update maven build configuration for 'sevntu-checks' module to run Checkstyle on the sources

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#309]
When maven build is executed Checkstyle checks should be run on the `sevntu-checks` sources like it is done in the main project.

This will allow us:
1. To automate code format validation
2. To resolve Checkstyle violations on the earlier stage (even before pull request)
3. To simplify movement checks into the main project

**Comment by damianszczepanik** [comment]
Duplicate of #310 ?

**Comment by romani** [comment]
Looks like duplicates and created at the same day. @rdiachenko , please confirm your proposals.

**Comment by rnveach** [comment]
Closing as a duplicate of #310 which is finished
