### ISSUE TITLE
OverridableMethodInConstructorCheck does not parse MyClass.this.myMethod() construction

### ISSUE THREAD

**Issue by damianszczepanik** [sevntu-checkstyle/sevntu.checkstyle#317]
I found that when we change line
    `this.accept(new File("1.txt"));`
to
    `Object1.this.accept(new File("1.txt"));`
from
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputOverridableMethodInConstructor13.java#L27

Then violation is not triggered. Correct me if I'm wrong but both constructions works the same.

**Comment by romani** [comment]
@damianszczepanik , :) yes it is bug in Check, we forgot about such case . I have not seen such code ever but as it is possible we might update Check to cover that too.

**Comment by damianszczepanik** [comment]
Sometimes this is the only way to get access to outer method from inner class. But this is true that this construction is not used often.
