### ISSUE TITLE
New Check: Enforce whitespace before array initializer

### ISSUE THREAD

**Issue by mkordas** [sevntu-checkstyle/sevntu.checkstyle#333]
It would be good to have a check that enforces whitespace before array initializer according to samples in [Google Java Style](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.8.3.1-array-initializers).

For example:

``` java
new int[] {0, 1, 2, 3}  // correct

new int[] { // correct         
  0, 1, 2, 3          
}

new int[]
    {0, 1, 2, 3}  // correct

new int[]{ // incorrect         
  0, 1, 2, 3          
}

new int[]{0, 1, 2, 3}  // incorrect                           
```

Initially proposed in checkstyle/checkstyle#524

**Comment by romani** [comment]
merged.

**Comment by romani** [comment]
I need to reopen this issue I as we need to udpate all configuration files - for eclipse-cs, sonar, .... please look at other new Check introductions commits.

**Comment by rnveach** [comment]
Closing as all checks are in eclipse-cs/sonar since Pull #487 and Pull #495
