### ISSUE TITLE
RequiredParameterForAnnotationCheck: properties description is missed in eclipsecs-sevntu-plugin

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#356]
![requiredparameterforannotationinfo](https://cloud.githubusercontent.com/assets/875939/8086671/7ad68676-0f8e-11e5-80bf-5887b60b8297.png)

**Comment by rnveach** [comment]
This was fixed in https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/46a33f8ad4da433fda0a6df21d1693cfab8975a9#diff-9021f5acf59b458ce47769aedf500622L14 .
Property name forgot `For` in the check's name.

Closing.
