### ISSUE TITLE
NameConventionForJunit4TestClassesCheck: properties description is missed in eclipsecs-sevntu-plugin

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#357]
![nameconventionforjunit4testclassescheck](https://cloud.githubusercontent.com/assets/875939/8087308/fb323a6a-0f91-11e5-9073-b0524c643a09.png)

**Comment by rnveach** [comment]
This was fixed in https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/46a33f8ad4da433fda0a6df21d1693cfab8975a9#diff-41027f58a40e7f9572f62d5e7c281134R311 .
Property name was incorrectly set as `correctTestClassNameRegex` and was renamed to `expectedClassNameRegex`.

Closing.
