### ISSUE TITLE
New check: only one break or continue statement should be inside cycle body

### ISSUE THREAD

**Issue by sabaka** [sevntu-checkstyle/sevntu.checkstyle#374]
Restricting the number of break and continue statements in a loop is done in the interest of good structured programming.

One break and continue statement is acceptable in a loop, since it facilitates optimal coding. If there is more than one, the code should be refactored to increase readability.

inspired by: http://nemo.sonarqube.org/coding_rules#languages=java|q=one%20break

that rule already enforced over Checkstyle codebase.

**Comment by yaziza** [comment]
Hi, i wanna contribute to the project and i think this issue can be a good starting  as it s labeled easy.

Can you please give some hint where to start ?
Thank you !

**Comment by romani** [comment]
new contributors are always welcome.

please read https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki
http://checkstyle.sourceforge.net/extending.html
http://checkstyle.sourceforge.net/contributing.html
http://checkstyle.sourceforge.net/beginning_development.html

please join this mail-list https://groups.google.com/forum/#!forum/sevntu-checkstyle , open topic , an there will discuss all your questions and problems.

**Comment by yaziza** [comment]
Hi, i have started working on this issue, i will fix all checkstyle violations and write unit tests on the next few days. Feedback highly appreciated :)

**Comment by romani** [comment]
please finish with checkstyle violations first and then share a link for review.

**Comment by romani** [comment]
merged.
