### ISSUE TITLE
VariableDeclarationUsageDistance error with parsing configuration xml file with IDEA version

### ISSUE THREAD

**Issue by C4rt** [sevntu-checkstyle/sevntu.checkstyle#376]
The reason for my problem is that the sevntu-checkstyle-default-configuration.xml linked in the current version of the GitHub wiki document seems outdated and generates error with the VariableDeclarationUsageDistance check.

**Comment by romani** [comment]
Thanks for reporting, fixed.

These Checks become a part of main library
