### ISSUE TITLE
upgrade to checkstyle 6.11.2 version

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#379]
upgrade https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L19 to 6.11 version to be the same as Eclipse-CS.

upgrade will cause UT failure https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/82769137#L638 , resolve it.

**Comment by igieon** [comment]
Probably could by closed
