### ISSUE TITLE
Cannot initialize module SingleSpaceSeparator

### ISSUE THREAD

**Issue by applepi07** [sevntu-checkstyle/sevntu.checkstyle#385]
Upon updating to 1.16.0 and attempting to include the new SingleSpaceSeparator check, eclipse throws the following error:
cannot initialize module SingleSpaceSeparator - Unable to instantiate 'SingleSpaceSeparator' class, ...

My guess is that this is because this file doesn't include the whitespace package
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/eclipsecs-sevntu-plugin/src/checkstyle_packages.xml

**Comment by romani** [comment]
failed to reproduce, but code is updated, released as 1.16.1.
