### ISSUE TITLE
Fix all javadoc problems and publish Javadoc at github.io

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#409]
We have no HTML documentation :( .
We could simply generate javadoc by "mvn javadoc:javadoc" and publish it at https://github.com/sevntu-checkstyle/sevntu.checkstyle/tree/gh-pages during deploy-all.sh 

Right now "mvn javadoc:javadoc" report a lot of  ERROR.
check for javadoc generation should be added to TravisCI build.

**Comment by daniilyar** [comment]
Full list of javadoc errors: http://pastebin.com/DSk2XXEC

**Comment by romani** [comment]
please do not forget to put "mvn javadoc:javadoc" to travis to avoid such problem in future.

**Comment by romani** [comment]
This is resolved in 1.21.0
