### ISSUE TITLE
AvoidModifiersForTypes throws Exception while processing modifier token which has type LITERAL_PRIVATE 

### ISSUE THREAD

**Issue by MEZk** [sevntu-checkstyle/sevntu.checkstyle#410]
AvoidModifiersForTypes throws Exception while processing modifier token which has type LITERAL_PRIVATE. The problem is appeared due to the fact that the check does not take into account LITERAL_PRIVATE modifier of the variable.

See https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/81a2cf91fbb1d2ec18ffd6f5cfc2bb67828c4834/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheck.java#L156 

**Configuration:**
```xml
<?xml version="1.0" ?>

<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="AvoidModifiersForTypes"/>
    </module>
</module>
```

**Input file:** https://github.com/checkstyle/checkstyle/blob/e8475b41261f724128c869b4de371713d86228c3/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java

SevNTU Checkstyle 1.17.1 output:

```
Exception was thrown while processing checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java: Found unsupported token: LITERAL_PRIVATE 
```

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@yaziza , your update is released, please enforce it over checkstyle code - https://github.com/checkstyle/checkstyle/issues/3064
