### ISSUE TITLE
New check: ConstructorWithoutParamsCheck to catch Throwable constructors usage with no arguments

### ISSUE THREAD

**Issue by zerg-junior** [sevntu-checkstyle/sevntu.checkstyle#412]
An exception message  must contain enough info to find out why an exception occurred (e.g. "Effective Java", item 63). So a check that forbids 
* using Throwable no-args constructors 
* passing empty String literals to Throwable constructors.

may be worth considering.

**Comment by romani** [comment]
first request should be done as general new Check - NoDefaultCtorUsage or smth similar
second request should be as EmptyExceptionMessage, user define regexp of how to distinguish classes from Exception/Error/Throwable

**Comment by zerg-junior** [comment]
@romani  I consider writing the `NoDefaultCtorUsage` check. Is anyone already working on it ?

> second request should be as EmptyExceptionMessage, user define regexp

This is the project-specific `RegExp` and not a new check, right ?

**Comment by romani** [comment]
@zerg-junior ,

> I consider writing the NoDefaultCtorUsage check. Is anyone already working on it ?

I try to keep assignments of issue (by comment or Assigneed field) if somebody what to implement issue.
Nobody is focused on this.
We do not have a constantly focused engineers on the project, you are always welcome to help with implementations

> This is the project-specific RegExp and not a new check, right ?

customized RegExp Check will not help to cover case reliably without false positives.
Special new Check will be more reliable but still not 100% working solution. Checkstyle have limitation and do not have information about Types and their hierarchy - we just have tree of strings.
http://checkstyle.sourceforge.net/writingchecks.html#Limitations
So wee need to help Check to catch Exception types by RegExp like ".*Exception|.*Error|.*Throwable" , if we find code like "new MyException("");" -- you raise an violation.
I could provide you more details and guide you through implementation, just let me know if you with to continue.

**Comment by zerg-junior** [comment]
> you are always welcome to help with implementations

Great, then please skim the following contract:

#### NoCtorWithoutParamsCheck

Prohibits usage of parameterless constructors, including the default ones.

Rationale: constructors of certain classes must always take arguments to properly instantiate objects. Exception classes are the primary example: their objects must  always contain enough info to find out why an exception occurred (see "Effective Java", item 63). Constructing an exception without a cause exception or an exception message leaves out such info and thus should be prohibited.

Configuration: via the `format` field of the `RegExp` type:
```xml
<module name="NoCtorWithoutParamsCheck">
  <property name="format" value=".*Exception|Clazz1"/>
</module>
```


###### Examples
```java
// the check can prohibit default constructors of built-in classes
RuntimeException ex = new RuntimeException(); // prohibited

// the check can prohibit default constructors of user-defined classes
public class Clazz1 {

}

Clazz1 o1 = new Clazz1(); // prohibited

// the check can prohibit  user-defined parameterless constructors 
public class Clazz1 {

  Clazz1() {
    foobar();
  }

}

Clazz1 o1 = new Clazz1(); // prohibited
```
###### Non-examples
```java
// here the cosntructor takes a String argument, albeit an empty one
RuntimeException ex = new RuntimeException(""); //allowed
```


Does it make sense ? I leave handling empty String literals to a separate check.

**Comment by romani** [comment]
> NoCtorWithoutParamsCheck

make a name ConstructorWithoutParamsCheck , name of the Check helps to find it easily. "No" is not required as Check just catch them , how to fix code is not a Check business.

> format

name of option and meaning of it should be clear without reading  documentation. I propose "typeNameFormat".

> Non-examples

I do not understand why this is not a example. All of them are examples that show user where violation will be and what cases we skip. User like to read examples rather then descriptions.

> Does it make sense ?

Just to let you consider one nuance. If we go by matching of class type by regexp it could mean that some false positives could appear if the same name (but different package) is used. We could extend a bit Check to ask user to define canonical name of type (com.mycompany.MyClass) and analyse imports to make sure that we matching "new MyClass()" of com.mycompany.MyClass and not matching com.yourcompany.MyClass. We already have such Checks , implementation is not a poblem. The only drawback is that it demands from user detailed configuration with full names. ".*Exception" is much easier :) . Both approaches a valid. 
What are your thoughts about this ? What way you will go ?

> I leave handling empty String literals to a separate check.

please create separate issue for this.

**Comment by zerg-junior** [comment]
> The only drawback is that it demands from user detailed configuration with full names. ".*Exception" is much easier :) . Both approaches a valid. 
What are your thoughts about this ? What way you will go ?

I actually need this check for exceptions, so I'll go with the reg exp.

**Comment by romani** [comment]
you are welcome.
issue is renamed to be ConstructorWithoutParamsCheck specific.

**Comment by zerg-junior** [comment]
@romani I suggest we leave the default config empty for this check. Is it reasonable ?

**Comment by romani** [comment]
I think it ok to make it ".*Exception" by default. Createion of exceprion without explanation is evil.

**Comment by zerg-junior** [comment]
@romani Seems plausible, I'll do it.

**Comment by romani** [comment]
let me know if you need help with implementation or IDE setup or ..... .
We have bunch of examples in code :) on how to make a Check.

**Comment by zerg-junior** [comment]
> let me know if you need help with implementation or IDE setup or 

In BaseCheckTestSupport, the [BriefLogger](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/test/java/com/github/sevntu/checkstyle/BaseCheckTestSupport.java#L35) calls the super() of DefaultLogger with the fifth parameter being `boolean`. The only 5-parameter [DefaultLogger constructor](http://checkstyle.sourceforge.net/apidocs/src-html/com/puppycrawl/tools/checkstyle/DefaultLogger.html#line.92) seems to expect an `AuditEventFormatter` value in this place. Hence compilation failure due to incompatible types.

Am I using an outdated version of the core checkstyle or miss some other library?

**Comment by romani** [comment]
Please look at our build system https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle it is green so it is compilable. Compare compilation process with it. If all the same please share with full log of compilation at gist.github.com

**Comment by zerg-junior** [comment]
@romani Does the following log message look meaningful to you ?

> Calls to constructors of ''{0}'' should use at least one parameter.

''{0}'' stands for the class name.

Also, does sevntu-checkstyle have any special contributor guidelines ?

**Comment by zerg-junior** [comment]
@romani [Pull request](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/428)

**Comment by romani** [comment]
>Does the following log message look meaningful to you ?

Yes, looks clear.

> does sevntu-checkstyle have any special contributor guidelines ?

Please rephrase a question, I do not understand it.

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@zerg-junior , your Check is released, please enforce it over checkstyle code - https://github.com/checkstyle/checkstyle/issues/3064
