### ISSUE TITLE
New check: ForbidThrowingGeneralExceptions

### ISSUE THREAD

**Issue by zerg-junior** [sevntu-checkstyle/sevntu.checkstyle#413]
Throwing general exceptions such as RuntimeException or Throwable might be worth prohibiting.

Related checks:
1. The sevntu repository already contains [IllegalCatchExtendedCheck](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java) that forbids  catching such exceptions.
2. The checkstyle [IllegalThrows](http://checkstyle.sourceforge.net/config_coding.html#IllegalThrows) partially covers this use case.

**Comment by romani** [comment]
it should be covered by http://checkstyle.sourceforge.net/config_coding.html#IllegalInstantiation
if not, lease describe a case.

**Comment by zerg-junior** [comment]
Thank you, Roman. The IllegalInstantiation check should help.

**Comment by romani** [comment]
If it covers your case , please close the issue
