### ISSUE TITLE
Rename checks to follow Checkstyle convention for check names

### ISSUE THREAD

**Issue by MEZk** [sevntu-checkstyle/sevntu.checkstyle#417]
https://github.com/checkstyle/checkstyle/issues/2780

Checkstyle name convension for checks names: ```XXXXCheck```

The following classes should be renamed:
AvoidDefaultSerializableInInnerClasses
ForbidCCommentsInMethods
ReturnBooleanFromTernary
ReturnNullInsteadOfBoolean

**Comment by romani** [comment]
fix is merged.
