### ISSUE TITLE
Add UniformEnumValueNameCheck

### ISSUE THREAD

**Issue by pbaranchikov** [sevntu-checkstyle/sevntu.checkstyle#445]
This check should accept multiple regular expressions for enum values and validate names to conform certain conventions but only one convention in one enum.

**Comment by romani** [comment]
Thanks a lot.

0)
> UniformEnumValueCheck

https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.9

"EnumConstant" ! We follow jdk names as much as possible.

1)
> public void visitToken(DetailAST ast)

logic should be simple but looks very complicated. Need to be re-factored to be a might be less efficient but friendly for human. 

please make it like:
```
enumValueTokens = getTokensbyType(TokenType.ENUM_CONSTANT_DEF);
final String enumName =  ....
BitSet matches = matchPatterns(enumName);
if (matches.isEmpty || matches.cardinality > 1) {
....
```
https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html#cardinality%28%29

such update will resolve extra "return" and extra "continue".

2)
I need separate PR for gh-pages branch, https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/List-of-files-that-need-to-be-updated-for-new-field-or-new-Check-implementation

**Comment by romani** [comment]
fix is merged.
