### ISSUE TITLE
ConstructorWithoutParamsCheck: update the default config

### ISSUE THREAD

**Issue by zerg-junior** [sevntu-checkstyle/sevntu.checkstyle#446]
Currently the check with the default config matches the pattern ".*Exception" anywhere in a class name. This leads to false positives such as in "MockExceptionHandler".

**Comment by zerg-junior** [comment]
[Pull request](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/447)

**Comment by rnveach** [comment]
Closing as fix was merged in referenced commit
