### ISSUE TITLE
enforce commit message format and issue reference in PR description

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#451]
this is already done in main project - https://github.com/checkstyle/checkstyle.

Need to be applied to this project too:
testing PR description - https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L329
testing of commit message - https://travis-ci.org/checkstyle/checkstyle/jobs/123016907#L799

**Comment by rnveach** [comment]
New items added:

1)
probably as next step idea:
review https://github.com/checkstyle/sonar-checkstyle/blob/master/.travis.yml , split of sevntu travis stuff into two files will give user ability to launch easily build item on his side.

2)
we need to question why we do "javadoc:javadoc" as separate step.
"mvn clean install" should be be enough.

**Comment by romani** [comment]
moved to #519 .

We should keep issues small and concise, that helps verification.

Current issue is done.
