### ISSUE TITLE
ReturnCountExtendedCheck takes into account 'returns' in lambdas

### ISSUE THREAD

**Issue by baratali** [sevntu-checkstyle/sevntu.checkstyle#463]
com.github.sevntu.checkstyle.checks.coding.ReturnCountExtendedCheck: Return count for 'load' method is 2 (max allowed is 1).

``` java
// code is not compilable
private static Integer load() {
    query((rs, rownum) -> {
        System.out.println();
        return p;
    });
    return a;
}
```

Similar issue for ReturnCountCheck: https://github.com/checkstyle/checkstyle/issues/1068

**Comment by romani** [comment]
Fix is merged
