### ISSUE TITLE
put a License to sevntu-checkstyle-maven-plugin 

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#475]
https://www.versioneye.com/user/projects/5504ca834a1064774400049a

```
Dependency 	Resolved 	Newest 	License
sevntu-checkstyle-maven-plugin 	1.21.1 	  UNKNOWN 	UNKNOWN 
```

license should be detectable.

**Comment by rnveach** [comment]
@romani Is this issue still valid? I don't see a `sevntu-checkstyle-maven-plugin`
https://github.com/sevntu-checkstyle/sevntu.checkstyle
