### ISSUE TITLE
enforce usage of all sevntu Check over sevntu-checks code

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#496]
first step is done - https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.travis.yml#L18

It is required to make all Checks to be severity ERROR in config https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/gh-pages/sevntu-checkstyle-default-configuration.xml . 

It is reasonable to move this config in master branch to let change config and introduce new Check in the same commit.

**Comment by romani** [comment]
config is introduced https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/sevntu-checks.xml
as copy from gh-pages.

It is required to start activation of rules one by one , to do so , please put `severity=error` for Check or remove `severity` property at all.
For now we have 38 deactivated Checks :).

**Comment by rnveach** [comment]
When latest PR is merged, the count will be at 11 deactivated checks.

**Comment by rnveach** [comment]
@romani I am at a stopping point with that last PR.

Only 4 checks remain.
`MultipleStringLiteralsExtended` and `LineLengthExtended` have legacy suppressions from similar checkstyle checks.
`ChildBlockLength`s only violation is in test.

If you wish, you can enable them and just suppress them.

**Comment by romani** [comment]
LineLengthExtended config is updated, violations looks reasonable to fix.
ChildBlockLength - should be fixed.
MultipleStringLiteralsExtended - ok to suppress.

**Comment by romani** [comment]
all Checks are activated to control new code, some legacy cases will be handled by separate issue - #525
