### ISSUE TITLE
Mention classpath separator platform dependency in the New issue template

### ISSUE THREAD

**Issue by george-007** [sevntu-checkstyle/sevntu.checkstyle#560]
In the New issue template It would be nice to mention that classpath separator is platform dependent.
It's `;` on windows but `:` on linux.

It tooked me a while to work it out;-)

### Windows
``
/var/tmp $ java -classpath sevntu-checks-X.XX.X.jar;checkstyle-X.XX-all.jar com.puppycrawl.tools.checkstyle.Main -c config.xml YOUR_FILE.java
``

### Linux
``
/var/tmp $ java -classpath sevntu-checks-X.XX.X.jar:checkstyle-X.XX-all.jar com.puppycrawl.tools.checkstyle.Main -c config.xml YOUR_FILE.java
``

**Comment by romani** [comment]
@george-007  , please send PR for https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.github/ISSUE_TEMPLATE.md update . To make it user friendly.

**Comment by rnveach** [comment]
Fix is merged
