### ISSUE TITLE
Draft a new release

### ISSUE THREAD

**Issue by thetric** [sevntu-checkstyle/sevntu.checkstyle#594]
The latest release `1.24.0` cannot be built, see [this JitPack.io build log](https://jitpack.io/com/github/sevntu-checkstyle/sevntu.checkstyle/1.24.0/build.log).
Could you please create a new working release?

**Comment by romani** [comment]
Our CI is green -  https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/builds/246682050

Build commands https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.travis.yml
