### ISSUE TITLE
CheckStylePluginException

### ISSUE THREAD

**Issue by AGordeevE** [sevntu-checkstyle/sevntu.checkstyle#613]
Hello everybody! 
I have a problem adding checkstyle-default-configuration.xml in my Idea:
org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be parsed.</b><br>SuppressionCommentFilter is not allowed as a child in Checker<br>The file has been blacklisted for 60s.</html>

Idea 2017.2.5
CheckStyle-IDEA plugin 5.10.2
sevntu-checkstyle-idea-extension-1.23.1
checkstyle-default-configuration.xml downloading here https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-use-SevNTU-Checkstyle-in-Intellij-IDEA

What can I do to fix it?

**Comment by romani** [comment]
you use checkstyle 8.2 .
In versions 8.X we started big API changes.
you have config that you used for checkstyle 7.X versions.

please skim http://checkstyle.sourceforge.net/releasenotes.html#Release_8.2 or http://checkstyle.sourceforge.net/releasenotes.html#Release_8.1 "Breaking backward compatibility"

you are affected by fix of https://github.com/checkstyle/checkstyle/issues/4714 

please read migration note in issue or stay on previous version of CheckStyle-IDEA/checkstyle.
