### ISSUE TITLE
Add no-exceptions testing lauches to CI

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#644]
when new Check is proposed in PR, after code-review almost forgot to request regression testing.
At least default execution of check should be done automatically on most our testing projects, as we do this at:
https://github.com/checkstyle/checkstyle/blob/master/wercker.yml

the same CIs could be used.

**Comment by rnveach** [comment]
>   groovy ./launch.groovy --listOfProjects projects-for-wercker.properties \
      --config checks-nonjavadoc-error.xml --checkstyleVersion ${SEVNTU_POM_VERSION}

Groovy scripts don't support `sevntuVersion`.

https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/pom.xml#L16
Default maven configuration uses release version, not snapshot version.
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/pom.xml#L15
Default maven configuration uses snapshot version for checkstyle.

We need to be able to override both values.

**Comment by romani** [comment]
Fix is merged
