### ISSUE TITLE
sevntu-checks.xml refers to old dtd

### ISSUE THREAD

**Issue by raghavgautam** [sevntu-checkstyle/sevntu.checkstyle#648]
I found that [sevntu-checks.xml ](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/sevntu-checks.xml#L2) still refers to an old(1.2) version of dtd. The current version is 1.3.

**Comment by rnveach** [comment]
The only difference between the 2 is allowing to override Check messages with custom ones.
Sevntu hasn't had need of this so there hasn't been any reason to upgrade.
Staying on old version doesn't hurt anything, neither does going to new version.

**Comment by raghavgautam** [comment]
@rnveach Ok.

**Comment by rnveach** [comment]
@raghavgautam If you wish to upgrade the version, you can go right ahead.

**Comment by rnveach** [comment]
Fix was merged
