### ISSUE TITLE
CustomDeclarationOrderCheck: Correct spelling of DeclareAnonClassField

### ISSUE THREAD

**Issue by jsoref** [sevntu-checkstyle/sevntu.checkstyle#656]
To date, the annotation is `DeclareAnnonClassField(...)`, but conceptually, it's trying to describe "declare an **anonymous** class field", the proper abbreviation for *anonymous* should be **anon**, not **annon** (which would be an abbreviation for `annonymous` [sic]), and thus the correct annotation should be `DeclareAnonClassField(...)`.

## Migration for users

If you use `DeclareAnnonClassField` in your configuration for this Check, please rename it to `DeclareAnonClassField`.

**Comment by rnveach** [comment]
@jsoref This doesn't explain anything like name of check being affected and why it is being renamed.
Please update issue and title to be more descriptive.

**Comment by romani** [comment]
@jsoref, please explain users how to migrate, what they should change in theirs config file. In your commit you have example, just place it to description

**Comment by rnveach** [comment]
I added migration section.

**Comment by romani** [comment]
fix is merged
