### ISSUE TITLE
Verify all modules are listed in contribution checks-sevntu-error.xml

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#691]
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-sevntu-error.xml
File hasn't been updated in a year. No exception testing at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/644 will verify it is defined correctly, but nothing is ensuring it is populated with all modules.

Ex: `MoveVariableInsideIfCheck` is missing.

**Comment by rnveach** [comment]
Checkstyle project looks at sevntu module list too at https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh#L148-L158 .
We should be able to use similar code to compare the 2 files.

**Comment by rnveach** [comment]
@romani New module in Checkstyle project is rare, but do we have a similar check against `checks-nonjavadoc-error.xml` and `checks-only-javadoc-error.xml`?

**Comment by rnveach** [comment]
https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/390207131#L532
New CI is reporting the following modules are missing:
````
+CheckstyleTestMakeup
+ForbidCertainMethod
+MoveVariableInsideIf
+RequireFailForTryCatchInJunit
````

**Comment by romani** [comment]
no objection to make to more automated

> but do we have a similar check against checks-nonjavadoc-error.xml and checks-only-javadoc-error.xml?

we should add.
It is high likelihood that we will forget to do this. 
and we have missed one already - AnnotationOnSameLine , that was added at 8.2 version.

**Comment by rnveach** [comment]
I will create issue in checkstyle.

**Comment by rnveach** [comment]
Fix was merged.
