### ISSUE TITLE
Improve JavadocMethod Check 

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#70]
Improve JavadocMethod check to cover only abstract methods, or only inheritable methods, or only final methods etc. 

http://sourceforge.net/tracker/index.php?func=detail&aid=2959656&group_id=29721&atid=397081

Additional request is to - Force users to write java doc for Interfaces/Abstract classes only.
http://sourceforge.net/tracker/?func=detail&aid=2959656&group_id=29721&atid=397081
http://stackoverflow.com/questions/13271326/checkstyle-check-only-method-in-interface

-----
UPDATE: Checkstyle supports 
https://checkstyle.org/config_filters.html#SuppressionXpathSingleFilter from 8.18
by means of fancy xpath expression we can exclude all not required violations while Check can not support it more easy way.

**Comment by Sebl29** [comment]
Hi,
I need to assure that every interface method is documented. Any news on that issue or the "new JavaDoc comments processing algorithm"?

**Comment by romani** [comment]
> "new JavaDoc comments processing algorithm"

It is implemented, examples:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java#L75
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java

but it is not yet used widely, as we have to much bugs in existing Checks, so we postponed refactoring of existing Checks. But you can help us, to make it available earlier.

**Comment by michaelboyles** [comment]
It's been six and a half years - is there any chance this will be implemented?

**Comment by rnveach** [comment]
Anyone is welcome to contribute to make it happen. That may be the only way it gets implemented.

**Comment by kaushal-khurana-17** [comment]
Hi, I am a beginner at this issue can you help me. How to start it?

**Comment by kaushal-khurana-17** [comment]
Can you help me?

**Comment by romani** [comment]
closing this as it is duplicate of https://github.com/checkstyle/checkstyle/issues/97
