### ISSUE TITLE
Checkstyle default configuration file link respond with 404

### ISSUE THREAD

**Issue by GrigoriyDidorenko** [sevntu-checkstyle/sevntu.checkstyle#710]
Hi!

- habra post: https://habr.com/sandbox/78503/
- Official site: http://sevntu-checkstyle.github.io/sevntu.checkstyle/
- All installation tutorials

points to the [checkstyle-default-configuration](https://raw.githubusercontent.com/sevntu-checkstyle/sevntu.checkstyle/gh-pages/sevntu-checkstyle-default-configuration.xml), which is deleted or moved.

Please update the link

**Comment by GrigoriyDidorenko** [comment]
In general, all your tutorials are pointing to the same link. I just want to download that config.

**Comment by romani** [comment]
http://roman-ivanov.blogspot.com/2013/11/?m=1

@VadimPanasiuk , can you update your article  on habrahabr ?

**Comment by romani** [comment]
All Checks are in use at https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/sevntu-checks.xml , you can use this configuration as example of how our team is using our own Checks.

**Comment by romani** [comment]
@GrigoriyDidorenko , please reference here all other articles with wrong link.

**Comment by GrigoriyDidorenko** [comment]
Article: [How to use SevNTU Checkstyle in Intellij IDEA](https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-use-SevNTU-Checkstyle-in-Intellij-IDEA)

> Download checkstyle-default-configuration.xml with all SevNTU checks with default configuration settings.

Article: [How to integrate sevntu checks into SonarQubeTM (user's guide)](https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-integrate-sevntu-checks-into-SonarQubeTM-%28user%27s-guide%29)

> In Quality Profiles tab create a new profile by importing sevntu-checkstyle-default-configuration.xml checkstyle configuration. Set profile as default

Article:[ How to use SevNTU Checkstyle in NetBeans](https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-use-SevNTU-Checkstyle-in-NetBeans)

> Download configuration xml-file for all SevNTU Checks. You can modify or delete Checks in this file. If you already have Checkstyle configuration file, copy all SevNTU Checks to this file. SevNTU checks are <module name="CheckName"> tags in <module name="TreeWalker"> tag, so you need to copy/modify only them.

**Comment by GrigoriyDidorenko** [comment]
Any update on missing file?

**Comment by romani** [comment]
@GrigoriyDidorenko , I am afk for this and probably next week. I updated link from phone. If smth is still wrong, let us know we will update later.

Looks like we lost connection with Vadim , if you have have account, please make a comment to post

**Comment by GrigoriyDidorenko** [comment]
thanks, that works
