### ISSUE TITLE
Restore validation of sevntu-checks on sonar

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#711]
>Hello dear open-source developers,
I'm Fabrice, from the SonarCloud team. I'm contacting you because you are the administrator of at least one project which:
belongs to the "Open Source" organization on SonarCloud
has not been analyzed for more than 6 months
In a very near future, we are going to drop this "Open Source" organization which does not make sense anymore because we introduced the possibility (last year) to create dedicated organizations (in which you can define your quality profiles and quality gates, manage your members, ...etc). Since some of your projects seem to be abandoned on this organization, we are planning to drop them at the end of August and I wanted to get the chance to warn you in advance.
Obviously, SonarCloud remains and will always remain free for open-source projects, so you are welcome to create new organizations and analyze your projects there!
Best regards,
Fabrice Bellingard | SonarSource
SonarCloud Product Manager

https://sonarcloud.io/dashboard?id=com.github.sevntu.checkstyle%3Asevntu-checks
Last analysis for this one is 2 years old

**Comment by romani** [comment]
new organization "checkstyle" was created , sevnu is placed under it https://sonarcloud.io/dashboard?id=com.github.sevntu-checkstyle%3Asevntu-checks

**Comment by rnveach** [comment]
Fix was merged
