### ISSUE TITLE
Release version 1.31.0

### ISSUE THREAD

**Issue by valfirst** [sevntu-checkstyle/sevntu.checkstyle#714]
Checkstyle `8.11.+` is not compatible with sevntu-checks `1.30.0` due to changes in Checkstyle class names. 
Are there any plans to release a new version?

**Comment by romani** [comment]
Yes, we need , but need help from community to move forward, too much activity for our tiny team.,
Please be welcome with PR.

**Comment by valfirst** [comment]
@romani , do you mean PR for release or any other features?

**Comment by romani** [comment]
Yes, PR for release, you can find examples in git history, actual deployment can be done only by maintainers

**Comment by rnveach** [comment]
@romani Which commits are you talking about? Nearly all commits done in sevntu for release are automated by bash script.

**Comment by romani** [comment]
We need to bump version of checkstyle and eclipse-cs (they should be in sync) and pass CI.

Sevntu versions bump is automated.

**Comment by valfirst** [comment]
> We need to bump version of checkstyle and eclipse-cs (they should be in sync) and pass CI.

Could you please point what else should be done in addition to https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/1d7df35e2d672b37d87ecc505f80bd3ffd809db9?

**Comment by rnveach** [comment]
we are in sync with eclipse-cs, which is currently at 8.11. See https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/712

**Comment by romani** [comment]
@valfirst , looks good on quick look.

Please do PR.

**Comment by rnveach** [comment]
@romani That code has already been merged, see issue I posted in previous comment.

**Comment by romani** [comment]
@rnveach , do you have all permissions to run release ? Or do you want me to do this.

**Comment by rnveach** [comment]
i still havent gotten maven access, but you can run it if you want.

**Comment by romani** [comment]
I did all steps up to point 6 from https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle , need to wait when artifacts become available online

**Comment by romani** [comment]
release 1.31.0 is done - http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.31.0
