### ISSUE TITLE
Fix length issue with sevntu modifying config on regression

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#718]
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/709#issuecomment-421063748

https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/411174590#L1048
> Travis failure is reproduced on my local on your branch (not in master):
> `<module name="com.github.sevntu.checkstyle.checks.coding.EnumTrailingCommaAndSemicolonCheck"></module>`

This is because this is the full regression test of new modules in Sevntu run on Checkstyle.
Specifically this happens in https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckstyleRegressionTest.java#L104 . We pull in checkstyle's repo and modify `checkstyle_sevntu_checks.xml` to include all new modules in sevntu PR that are not in checkstyle. This is how we know if a new check causes any violations on checkstyle once integrated.

See https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/411174590#L867
> -- Adding Check: com.github.sevntu.checkstyle.checks.coding.EnumTrailingCommaAndSemicolonCheck
-- Adding Suppression: EnumTrailingCommaAndSemicolonCheck

------------------

Because of the new formatting restrictions placed on the XML files, `CheckstyleRegressionTest` will have to be modified to split the module name up since we use the full package name.

**Comment by romani** [comment]
Fix is merged
