### ISSUE TITLE
Upgrade sonar-plugin-api to 6.7

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#763]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/958f809dc51447ab1d59a3f0d624f8a5338441f0/sevntu-checkstyle-sonar-plugin/pom.xml#L35-L37

Sevntu is using an old version of sonar-api. Checkstyle-sonar is on 6.7.
https://github.com/checkstyle/sonar-checkstyle/blob/master/pom.xml#L85

Some similar upgrades was done with checkstyle-sonar at https://github.com/checkstyle/sonar-checkstyle/commit/de7d6884e6184edc9b800ce3f662e941daebe907 , switching from rule repository to rules definition.

**Comment by romani** [comment]
If that make changes easy , we can jump to latest sonar lst version 7.9 .

If nobody complained about new API usage, no need to support not latest API.

**Comment by rdiachenko** [comment]
I'm on it.

**Comment by romani** [comment]
Fix is merged.
