### ISSUE TITLE
Extend ForbidCertainMethodCheck to support matching on fully-qualified name

### ISSUE THREAD

**Issue by PhilippWendler** [sevntu-checkstyle/sevntu.checkstyle#773]
Currently the [ForbidCertainMethodCheck](https://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheck.html) from #604 allows matching names of called methods using a regexp, but only the actual method name is matched. There are many cases where a specific method from a specific class should be forbidden, though, and this is not possible using the current check.

Example: Java provides `List.of()`/`List.copyOf` and similar methods for sets, but in our project we use Guava and would prefer people to use `ImmutableList.of()`/`ImmutableList.copyOf()` etc. (which have the same semantics but the advantage of making immutability visible in the returned type). Of course I cannot use ForbidCertainMethodCheck to forbid all methods named `of` and `copyOf`.

Even the original motivation of #604 was to forbid calls to `System.exit()` and `assertTrue`/`assertFalse` from JUnit (cf. discussions there), and this is used as example in the check's docs, but it is not actually possible to accomplish currently. One can only forbid all methods named `exit`, but this is often too coarse.

As implementation I would suggest to add another parameter named `fullyQualifiedName` to ForbidCertainMethodCheck, which could either be implemented as a list of names like `java.util.List.of,java.util.List.copyOf` or a regexp like `^java\.util\.List\.(of|copyOf)$`.

**Comment by romani** [comment]
I think you should be aware that Checkstyle is not type aware tool - https://checkstyle.org/writingchecks.html#Limitations, so we can not recognize type of `copyOf` method. Especially if it is statically imported. So this Check is prone to false positives and should be used with caution.

> fullyQualifiedName to ForbidCertainMethodCheck, which could either be implemented as a list of names like java.util.List.of,java.util.List.copyOf or a regexp like ^java\.util\.List\.(of|copyOf)$.

it might work only in case, in your code you always use method with fully qualified name, that I doubt.
Checkstyle just parse java file as text file (no type infomation at all) and just iterate over string values of AST (if name is `copyOf`  in code we will never get to know from what type it is).

**Comment by PhilippWendler** [comment]
Thanks for the answer. Of course the check is only meaningful if it matches even when the code in question uses an import.

However, before proposing the feature I saw the [IllegalInstantiationCheck](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.html) and that it for example matches `new Boolean()` (without fully qualified name) even if `java.lang.Boolean` is specified in the check configuration.
I do not know how that is [implemented](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java), but however it is done I guess the same approach should be possible for my proposed feature?

**Comment by romani** [comment]
here is a nuance ...
https://stackoverflow.com/questions/13009560/why-are-static-imports-of-static-methods-with-same-names-legal

it will be not ease to implement, but doable. There will be still high chance of false-positive. But if can find cases where we will have them and document them, and will find a way how user can suppress them, so it might be good.

You need to propose design change for a Check (imagine all is implemnted), with examples of behavior (config + source file with inlined comment on lines where violation is expected).

As proposal pass review of maintainers, we approve issue (so we are 90% sure in success), you can start implementing it. During acceptance of PR you will do aggressive testing (we will show how to do this almost automated) to make sure all works correctly.

**Comment by PhilippWendler** [comment]
Sorry, I don't have the time and Checkstyle knowledge to implement this myself. But I still think this check would be interesting for a lot of projects, given how many methods there are in the Java API that one should avoid in modern Java.

For now, I found a solution using [Google Refaster](https://errorprone.info/docs/refaster), which allows to write rules that match on certain method calls, but it is more difficult to set up.

**Comment by PhilippWendler** [comment]
Another tool I found that does exactly this and is less effort to use than Refaster is the [Forbidden API Checker](https://github.com/policeman-tools/forbidden-apis).

So I am retracting the feature request given that it is difficult to implement with Checkstyle and other tools exist.
