### ISSUE TITLE
Support Junit5 in RequireFailForTryCatchInJunit

### ISSUE THREAD

**Issue by pbludov** [sevntu-checkstyle/sevntu.checkstyle#789]
Check [RequireFailForTryCatchInJunit](http://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.html)

$ cat TestClass.java
```
import org.junit.jupiter.api.Test; // Not org.junit.Test

class InputRequireFailForTryCatchInJunit5Check {
    @Test
    public void method() {
        try {
            System.exit(0);
        }
        catch (Exception ignored) {
        }
    }
}
```
$ cat TestConfig.xml
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="RequireFailForTryCatchInJunit"/>
  </module>
</module>
```
$java -classpath sevntu-checks-1.36.0.jar:checkstyle-8.28-all.jar com.puppycrawl.tools.checkstyle.Main -c TestConfig.xml TestClass.java`
```
Starting audit...
Audit done.
```
Expected violation:
```
[ERROR] TestClass.java:6:9: try/catch either requires a fail at the end of the try clause for junit tests or to remove the try/catch completely. [RequireFailForTryCatchInJunit]
```

Junit 5 API provides new `@Test` annotation in package `org.junit.jupiter.api`. The check should be aware of this annotation.

**Comment by romani** [comment]
fix is merged.
