### ISSUE TITLE
Remove usages of `DetailAST::getNumberOfChildren`

### ISSUE THREAD

**Issue by pbludov** [sevntu-checkstyle/sevntu.checkstyle#793]
The interface `DetailAST` currently contains two methods to return the count of children:

* [getChildCount](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java#L36)
* [getNumberOfChildren](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java#L119)

Both methods are implemented in the same way (`getChildCount` has an optimization):

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L166

https://github.com/Distrotech/antlr2/blob/master/antlr/BaseAST.java#L67

We should drop one of them in the future. In the meantime, let's update the code to use only the optimized version.

**Comment by rnveach** [comment]
> getNumberOfChildren
> BaseAST.java

I agree if they are the same and this method is coming from ANTLR. It will most likely go away if we ever upgrade to newer antlr and would have to re-implement it.

**Comment by rnveach** [comment]
@pbludov Do you plan to make same issue in main library?

**Comment by pbludov** [comment]
> @pbludov Do you plan to make same issue in main library?

Yes, this method should be deprecated in the main library. And later removed.

**Comment by romani** [comment]
@pbludov , is this issue done ?

**Comment by pbludov** [comment]
> @pbludov , is this issue done ?

This issue is done, `node.getFirstChild() != null` should be replaced with `node.hasChildren()` after next release of Checkstyle.
