### ISSUE TITLE
Please update old link in wiki page

### ISSUE THREAD

**Issue by 1951FDG** [sevntu-checkstyle/sevntu.checkstyle#807]
Please refer to wiki page:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-use-SevNTU-Checkstyle-in-Intellij-IDEA#download-configuration-file-for-checkstyle-idea

Please refer to text on page:
Download latest sevntu-checkstyle-idea-extension-X.XX.X.jar from our **repository**.

**Repository** links to:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/tree/gh-pages/maven2/com/github/sevntu/checkstyle/sevntu-checkstyle-idea-extension

**Repository** should link to:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/tree/gh-pages/maven2/com/github/sevntu-checkstyle/sevntu-checkstyle-idea-extension

**Comment by romani** [comment]
@1951FDG , thanks a lot !!

fixed, I also added https://repo1.maven.org/maven2/com/github/sevntu-checkstyle/sevntu-checkstyle-idea-extension/

**Comment by 1951FDG** [comment]
@romani Thanks!
