### ISSUE TITLE
RequireFailForTryCatchInJunit does not handle wildcard import of static fail method

### ISSUE THREAD

**Issue by sebthom** [sevntu-checkstyle/sevntu.checkstyle#817]
**/var/tmp $ javac YOUR_FILE.java**

**/var/tmp $ cat YOUR_FILE.java**

```java
import static org.junit.Assert.*;
import org.junit.Test;

public class YOUR_FILE {
    @Test
    public void junit4Test() {
        try {
            fail();
        }
        catch (Exception expected) {
        }
    }
}
```

**/var/tmp $ cat config.xml**
```xml
<module name="Checker">
  <module name="TreeWalker">
    <module name="RequireFailForTryCatchInJunitCheck" />
  </module>
</module>
```

**C:\tmp> java -classpath sevntu-checks-1.37.1.jar;checkstyle-8.32-all.jar com.puppycrawl.tools.checkstyle.Main -c config.xml YOUR_FILE.java**
```
Starting audit...
[ERROR] C:\tmp\YOUR_FILE.java:7:9: try/catch either requires a fail at the end of the try clause for junit tests or to remove the try/catch completely. [RequireFailForTryCatchInJunit]
Audit done.
Checkstyle ends with 1 errors.
```
---------------

Expected:
That the audit completes without errors. As the `RequireFailForTryCatchInJunit` rule actually is satisfied.

--------------

**Comment by romani** [comment]
@sebthom , thanks a lot for fix.
We usually release right after fixes to let contributors to use their work immediately.
But currently we experiencing high load of PR in main project, so I try to postpone something that can be postponed.
Is it ok if I delay release ?

**Comment by sebthom** [comment]
@romani no problem.

**Comment by sebthom** [comment]
@romani would it be possible for you to create a new release?

**Comment by romani** [comment]
@sebthom , no problem, sorry for delay.

**Comment by romani** [comment]
http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.38.0

**Comment by sebthom** [comment]
awesome, thanks!
