### ISSUE TITLE
New Check "Prefer method reference to lambda"

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#825]
copy from https://github.com/checkstyle/checkstyle/issues/120
implementation at https://github.com/checkstyle/checkstyle/pull/8232
we need to copy implementation as is in sevntu project (with senvtu specific modifications).
I will not require all updates as requested in PR as level of quality in sevntu is less and we keep controversial/incomplete Checks in senvtu for a reason.

-------

Playing with Java8 it seems to me that methods references are much more readable then lambdas. Of cause they can not be used everywhere as a replacement to lambdas, but in many places where lambda is used - method reference will be much more readable and shorter option. Consider implementing such a check for Java8.

Example:

``` java
list.foreach(s -> System.out.println(s));
list.foreach(System.out::println);
```
##

**Comment by aakarshvats638** [comment]
Sir, I would like to work on this issue, can you please elaborate on what I have to do?

**Comment by aakarshvats638** [comment]
Sir, I would like to work on this issue, can you please elaborate on what I have to do? @romani

**Comment by romani** [comment]
we just need to move implementation at checkstyle/checkstyle#8232 to this repository.
Implementation was good enough, we did not merged it to main repo only because it was very controversial.

**Comment by AkMo3** [comment]
@aakarshvats638, if you are not working on it, may I take over this issue?

**Comment by romani** [comment]
Merged

**Comment by romani** [comment]
@AkMo3 , thanks a lot for your time to make happen

https://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/com/github/sevntu/checkstyle/checks/coding/PreferMethodReferenceCheck.html

**Comment by AkMo3** [comment]
@romani It is my pleasure. Kudos to you and entire checkstyle member team for being so much so supportive and guiding us at every step.
