### ISSUE TITLE
Update Site Broken?

### ISSUE THREAD

**Issue by sebthom** [sevntu-checkstyle/sevntu.checkstyle#856]
I am trying to install sevntu.checkstyle via the documented update-site but eclipse fails with

```
!ENTRY org.eclipse.equinox.p2.artifact.repository 4 1000 2021-07-09 21:08:20.650
!MESSAGE No repository found at https://sevntu-checkstyle.github.com/sevntu.checkstyle/update-site/
```

https://sevntu-checkstyle.github.com/sevntu.checkstyle/update-site/p2.index returns 404

Did the URL change?

**Comment by rnveach** [comment]
Where did you find the URL? It has been on github pages for a while.

Our github pages is at https://sevntu-checkstyle.github.io/sevntu.checkstyle/ and the update site should be https://sevntu-checkstyle.github.io/sevntu.checkstyle/update-site/ . There is no index, hence the 404, but you can open `site.xml` which is what eclipse will be loading, not the index page.

@romani I couldn't find this link on the main page. Maybe we should add it. The picture on the main page has the old update site URL which should be replaced.

**Comment by sebthom** [comment]
@rnveach Ah nice, that works, thanks!

I got the base URL from the right content column of the repo home at `https://github.com/sevntu-checkstyle/sevntu.checkstyle`

![image](https://user-images.githubusercontent.com/426959/125186773-8ef82e80-e22c-11eb-8ae9-e5480a162f12.png)

So I guess there is a typo and it should say _sevntu-checkstyle.github.**io**_ instead of _sevntu-checkstyle.github.**com**_ there

**Comment by romani** [comment]
Link is fixed
