### ISSUE TITLE
Any version planned to be compatible with Checkstyle 9.2

### ISSUE THREAD

**Issue by Dichotomia** [sevntu-checkstyle/sevntu.checkstyle#877]
Hi all,

And Congratulations for all the work done.

The fix for checkstyle 9.2 has been integrated here https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/876

Any idea when will be the next release of sevntu.checkstyle?

Keep up the good work.

Best regards

**Comment by romani** [comment]
I waited for https://github.com/checkstyle/eclipse-cs/pull/330

To let all packages in sevntu be released to support checkstyle 9 .

But looks like eclipse part is stuck

**Comment by romani** [comment]
some activity is resumed, I hope there will be few releases soon from plugin to let catch up  9.x

**Comment by Dichotomia** [comment]
Good news!

**Comment by PhilippWendler** [comment]
Version 1.41.0 seems to work with Checkstyle 9.2 in my tests.

**Comment by Dichotomia** [comment]
I will try it.

**Comment by romani** [comment]
I am closing this for now,
Next release will be with eclipssecs above 9.2.1 as that version will have huge performance fix in core checkstyle.
