### ISSUE TITLE
satelite projects should use latest checkstyle as soon at is appears in maven repo

### ISSUE THREAD

**Issue by Rahulkhinchi03** [sevntu-checkstyle/sevntu.checkstyle#893]
Right now we do bump a version in a few projects https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#update-for-released-version-reference right after release.

Let's find a way to define in pom.xml the latest snapshot and most recent version. And the latest released version when we define dependencies. To let us skip such updates at all.

CI of such projects should be able to get the latest version from https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml and run projects with such version.

We can have in all such repos, a GitHub action that runs once a day check https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml, put such values in required files, and send PRs with changes (PR is necessary as we need notice is any problems happens if we introduce breaking changes)

TASK:

- [ ] Version Bump in `sevntu-checks/pom.xml`
- [ ] Version Bump in `sevntu-checkstyle-sonar-plugin/pom.xml`

**Comment by romani** [comment]
it works - https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/b621b30dfeb6ff1a57b7f879ccc79bbe9bf400b8
