### ISSUE TITLE
Remove deprecated method DefaultConfiguration::addAtrribute from code

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#901]
Identified at https://github.com/checkstyle/checkstyle/issues/11722 , we must remove code from sevntu.

**Comment by rnveach** [comment]
`CheckstyleTestMakeupCheck` also has to change for the new property.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/1aa955c047cabdec6d2c6bb16d4b2c10e9a17b4b/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheck.java#L254

**Comment by romani** [comment]
Fixmered
