### ISSUE TITLE
Upgrade eclipse-cs version to 10.4

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#930]
Eclipse-cs has been making releases, so we need to update the version here.

We should wait to see if eclipse-cs goes all the way to 10.4.

When we do update, we need to make sure we are consistent with https://github.com/checkstyle/eclipse-cs/issues/348#issuecomment-1298434963 .

**Comment by romani** [comment]
Fix is merged
