### ISSUE TITLE
bump-cs-version missed eclipsecs-sevntu-plugin

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#936]
Identified at 
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/eclipsecs-sevntu-plugin/pom.xml#L31
from commit 3fd82687ba33a238c9df03d6f9a778481864b3ae

This was a new addition at 220bf2a14fefef54e46b3345fc4862ce1aa69e00 due to a reported bug and was missed being added to bump-cs-version before its next run which resulted in the missed change at location mentioned above.

The main point of this issue is to expand `bump-cs-version.yml` for the new area to bump the checkstyle version when the YML is run. The above POM can also be updated as part of this issue in a separate commit.

https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.github/workflows/bump-cs-version.yml

**Comment by rnveach** [comment]
@romani If you agree, I think @stoyanK7 can work on this as part of the project

**Comment by romani** [comment]
Issue is created checkstyle/contribution#694

**Comment by romani** [comment]
Fix is merged
