### ISSUE TITLE
'Bump CS version in REPO' is not working

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#943]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/actions/runs/3602122111/jobs/6068698973#step:4:16128

```
Error:  Cannot resolve project dependencies:
Error:    Software being installed: eclipsecs-sevntu-plugin 1.43.0
Error:    Missing requirement: eclipsecs-sevntu-plugin 1.43.0 requires 'osgi.bundle; net.sf.eclipsecs.checkstyle 0.0.0' but it could not be found
```

**Comment by romani** [comment]
@stoyanK7 , please help to resolve

**Comment by stoyanK7** [comment]
On it.

**Comment by stoyanK7** [comment]
Aight, I am stuck on this one. No ideas on what to do. Locally no issues, but actions fails.

**Comment by rnveach** [comment]
@stoyanK7 Looking at error message, it looks like the original eclipsecs is not being installed first before doing an action eclipsecs-sevntu. You may have done this already on your local, but server starts with a clean system.

**Comment by rnveach** [comment]
I would assume something like https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/048cf5a21715dcb53d873c27f7eaf9985880092e/.ci/validation.sh#L20-L25 has to happen first.

**Comment by stoyanK7** [comment]
Yes, thank you. I was just looking at this. https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/SevNTU-plugin-for-EclipseCS-plugin-compilation
